---
inputs:
- type: git
  branch: master
  service: ${DEFINITION_REPO}
  path: .tekton
triggers:
- type: git
  name: Trigger
  service: ${DEFINITION_REPO}
  branch: master
  events: {"push":true,"pull_request":true,"pull_request_closed":false}
  eventListener: ci-listener
- type: manual
  name: Manual Trigger
  eventListener: ci-listener
properties:
- name: apikey
  value: ${API_KEY}
  type: SECURE
- name: cluster
  value: ${PROD_CLUSTER_NAME}
  type: text 
- name: registryNamespace
  value: ${REGISTRY_NAMESPACE}
  type: text 
- name: clusterNamespace
  value: ${PROD_CLUSTER_NAMESPACE}
  type: text
- name: clusterRegion
  value: ${PROD_REGION_ID}
  type: text
- name: registryRegion
  value: ${REGISTRY_REGION_ID}
  type: text
- name: repository
  value: ${APP_URL}
  type: text
- name: revision
  value: ${REVISION}
  type: text
- name: definitionRepo
  value: ${DEFINITION_REPO}
  type: text
- name: apprepo
  value: ${APP_URL}
  type: text  
- name: servicenowtoken
  value: ${SERVICE_NOW_TOKEN}
  type: SECURE
- name: gheIssueRepo
  value: ${GHE_ISSUES_REPO}
  type: text 
- name: gheUser
  value: ${GHE_USER}
  type: text
- name: gheToken
  value: ${GHE_TOKEN}
  type: SECURE
- name: ghEmergencyLabel
  value: ${EMERGENCY_LABEL}
  type: text
- name: dockerConfigJson
  value: ${ARTIFACTORY_TOKEN}
  type: text
