version: '2'
messages:
  $i18n: locales.yml
template:
  name:
    $ref: "#/messages/template.name"
  description:
    $ref: "#/messages/template.description"
  header: '![](toolchain.svg?localize)'
  icon: secure-lock-kubernetes.svg
  required:
    - build
    - app-repo
    - tekton-pipeline-repo
    - evidence-repo
    - issue-repo
    - dra
  info:
    git url: >
      "[" + $env.repository + "]" +
        "(" + $env.repository + ")"
    git branch: >
      "[" + $env.branch + "]" +
        "(" + $env.repository +
          "/tree/" + $env.branch + ")"
toolchain:
  name: 'simple-tekton-toolchain-{{timestamp}}'
  template:
    getting_started:
      $ref: "#/messages/template.gettingStarted" 
services:
  tekton-pipeline-repo:
     service_id: github_integrated
     parameters:
       repo_name: 'tekton-poc-pipeline'
       repo_url: 'https://github.ibm.com/cocoa/tekton-poc-pipeline'
       type: clone
       has_issues: false
       enable_traceability: true
       legal: true
  app-repo:   
     service_id: github_integrated  
     parameters:
       repo_url: 'https://github.ibm.com/cocoa/cocoa-example-app'
       type: link
       has_issues: false
       enable_traceability: true
       legal: true
  issues-repo:
    service_id: github_integrated
    parameters:
      repo_name: 'issues-{{toolchain.name}}'
      type: new
      has_issues: false
      enable_traceability: true
      legal: true
  evidence-repo:
    service_id: github_integrated
    parameters:
      repo_name: 'evidence-{{toolchain.name}}'
      type: new
      has_issues: false
      enable_traceability: true
      legal: true
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: '{{services.repo.parameters.repo_name}}'
      type: tekton
      ui-pipeline: true
      configuration:
        content:
          $text: tekton.yaml
        env:
          CF_APP_NAME: '{{form.pipeline.parameters.app-name}}'
          REGISTRY_REGION_ID: '{{form.pipeline.parameters.registry-region}}'
          REGISTRY_NAMESPACE: '{{form.pipeline.parameters.registry-namespace}}'
          API_KEY: '{{form.pipeline.parameters.api-key}}'
          PROD_REGION_ID: '{{form.pipeline.parameters.prod-region}}'
          PROD_CLUSTER_NAME: '{{form.pipeline.parameters.prod-cluster-name}}'
          PROD_CLUSTER_NAMESPACE: '{{form.pipeline.parameters.prod-cluster-namespace}}'
          REVISION: master
          DEFINITION_REPO: tekton-pipeline-repo
          APPLICATION_REPO: '{{services.app-repo.parameters.source_repo_url}}'
          SERVICE_NOW_TOKEN: '{{services.app-repo.parameters.service_now_token}}'
        execute: true
  webide:
    service_id: orion 
  dra:
    service_id: draservicebroker
form:
  pipeline:
    parameters:
      app-name: '{{services.repo.parameters.repo_name}}'
      prod-cluster-namespace: prod
    schema:
      $ref: deploy.json
